# Generated by Django 6.0.7 on 2026-08-03 18:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('senderos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaminata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traza', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('distancia_km', models.FloatField(default=0)),
                ('duracion_segundos', models.PositiveIntegerField(default=0)),
                ('velocidad_promedio', models.FloatField(default=0)),
                ('numero_pasos', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('sendero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='senderos.sendero')),
            ],
        ),
    ]
