# Generated by Django 6.0.7 on 2026-09-04 19:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senderos', '0003_alter_sendero_geometria'),
        ('sesiones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesioncaminata',
            options={'ordering': ['-iniciado_en']},
        ),
        migrations.RenameField(
            model_name='sesioncaminata',
            old_name='fecha_inicio',
            new_name='iniciado_en',
        ),
        migrations.RenameField(
            model_name='sesioncaminata',
            old_name='numero_pasos',
            new_name='pasos',
        ),
        migrations.RenameField(
            model_name='sesioncaminata',
            old_name='velocidad_promedio',
            new_name='velocidad_promedio_kmh',
        ),
        migrations.AddField(
            model_name='sesioncaminata',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En curso'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='en_curso', max_length=15),
        ),
        migrations.AddField(
            model_name='sesioncaminata',
            name='finalizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesioncaminata',
            name='tiempo_pausado_segundos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sesioncaminata',
            name='sendero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='senderos.sendero'),
        ),
        migrations.AlterField(
            model_name='sesioncaminata',
            name='traza',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='sesioncaminata',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_caminata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PuntoGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('capturado_en', models.DateTimeField()),
                ('precision_m', models.FloatField(blank=True, null=True)),
                ('altitud_m', models.FloatField(blank=True, null=True)),
                ('velocidad_mps', models.FloatField(blank=True, null=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='sesiones.sesioncaminata')),
            ],
            options={
                'ordering': ['capturado_en'],
            },
        ),
    ]
