# Generated by Django 6.0.7 on 2026-09-05 19:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0003_alter_sesioncaminata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntogps',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
