# Generated by Django 6.0.7 on 2026-09-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0004_alter_puntogps_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaminata',
            name='numero_usuario',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
