# Generated by Django 6.0.7 on 2026-09-28 17:12

from django.db import migrations

def asignar_numeros(apps, schema_editor):
    Sesion = apps.get_model('sesiones', 'SesionCaminata')

    # order_by() vacío: el ordering por defecto del modelo rompería el distinct()
    usuarios_ids = Sesion.objects.order_by().values_list('usuario_id', flat=True).distinct()

    for uid in usuarios_ids:
        finalizadas = Sesion.objects.filter(usuario_id=uid, estado='finalizada').order_by('iniciado_en', 'id')
        for n, sesion in enumerate(finalizadas, start=1):
            sesion.numero_usuario = n
            sesion.save(update_fields=['numero_usuario'])

class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0005_sesioncaminata_numero_usuario'),
    ]

    operations = [
        migrations.RunPython(asignar_numeros, migrations.RunPython.noop),
    ]
