# Generated by Django 6.0.7 on 2026-08-03 18:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('senderos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitud', models.FloatField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('deterioro', 'Deterioro del camino'), ('senalizacion', 'Señalización deficiente'), ('residuos', 'Acumulación de residuos'), ('obstaculo', 'Obstáculo'), ('seguridad', 'Riesgo de seguridad')], max_length=20)),
                ('descripcion', models.TextField()),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('validado', models.BooleanField(default=False)),
                ('votos_confirmacion', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sendero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='senderos.sendero')),
            ],
        ),
    ]
