# Generated by Django 6.0.7 on 2026-09-06 17:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='reporte',
            name='distancia_sendero_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FotoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reportes/')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='reportes.reporte')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
