# Generated by Django 6.0.7 on 2026-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_options_remove_reporte_foto_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='validado',
        ),
        migrations.AddField(
            model_name='reporte',
            name='comentario_admin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15),
        ),
    ]
