# Generated by Django 6.0.7 on 2026-08-03 18:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sendero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('geometria', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('dificultad', models.CharField(max_length=20)),
                ('longitud_km', models.FloatField()),
                ('tiene_iluminacion', models.BooleanField(default=False)),
                ('horario_apertura', models.TimeField(blank=True, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En mantenimiento'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
