# Generated by Django 6.0.7 on 2026-08-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senderos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendero',
            options={'ordering': ['-creado_en']},
        ),
        migrations.RenameField(
            model_name='sendero',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='sendero',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sendero',
            name='canton',
            field=models.CharField(blank=True, default='Loja', max_length=100),
        ),
        migrations.AddField(
            model_name='sendero',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='senderos/portadas/'),
        ),
        migrations.AlterField(
            model_name='sendero',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sendero',
            name='dificultad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='sendero',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('alerta', 'Con alertas menores'), ('critico', 'Crítico')], default='bueno', max_length=10),
        ),
        migrations.AlterField(
            model_name='sendero',
            name='longitud_km',
            field=models.FloatField(default=0),
        ),
    ]
