# Generated by Django 6.0.7 on 2026-08-24 19:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senderos', '0002_alter_sendero_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendero',
            name='geometria',
            field=django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326),
        ),
    ]
