# Generated by Django 6.0.7 on 2026-10-06 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('reportes', '0004_remove_reporte_validado_reporte_comentario_admin_and_more'),
        ('senderos', '0004_sendero_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='enviada',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='notificaciones/'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', max_length=12),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='reportes.reporte'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento de la aplicación'), ('sendero', 'Aviso sobre un sendero'), ('seguridad', 'Aviso de seguridad'), ('comunicado', 'Comunicado a la comunidad'), ('proximidad', 'Incidencia cercana'), ('acumulacion', 'Reportes acumulados en un sendero'), ('estado_sendero', 'Cambio de estado de un sendero')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='sendero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='senderos.sendero'),
        ),
        migrations.CreateModel(
            name='NotificacionLeida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='notificaciones.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'notificacion')},
            },
        ),
    ]
