# Generated by Django 6.0.7 on 2026-08-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_codigoverificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
