# Generated by Django 6.0.7 on 2026-08-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_apellido_remove_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoverificacion',
            name='tipo',
            field=models.CharField(choices=[('verificacion', 'Verificación de cuenta'), ('recuperacion', 'Recuperación de contraseña')], default='verificacion', max_length=20),
        ),
    ]
