# Generated by Django 6.0.7 on 2026-09-28 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reporte_creado', 'Reporte creado'), ('perfil_actualizado', 'Perfil actualizado'), ('recorrido_finalizado', 'Recorrido finalizado'), ('descarga_pdf_estadisticas', 'Descarga de estadísticas (PDF)'), ('sendero_creado', 'Sendero creado'), ('sendero_actualizado', 'Sendero actualizado'), ('sendero_eliminado', 'Sendero eliminado'), ('descarga_pdf_historial', 'Descarga de historial (PDF)'), ('notificacion_creada', 'Notificación creada')], max_length=30)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
